Settings:
  # Quanta durabilità viene ripristinata ogni secondo in acqua
  water-repair-amount: 20
  # Probabilità (da 0.0 a 1.0) che il piccone perda durabilità
  durability-loss-chance: 0.25

Messages:
  energy-empty: "ENERGIA ESAURITA - RICARICA IN ACQUA"